sudo: required 
services:
    - docker
before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
    - docker build -t bebeverido/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true bebeverido/react-test npm test 
after_sucess:
    - docker build -t bebeverido/multi-client ./client
    - docker build -t bebeverido/multi-nginx ./nginx
    - docker build -t bebeverido/multi-server ./server
    - docker build -t bebeverido/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
    - docker push bebeverido/multi-client
    - docker push bebeverido/multi-nginx 
    - docker push bebeverido/multi-server
    - docker push bebeverido/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-606695939007'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
